name: CI

on:
  push:
    paths:
      - '.github/**'
      - 'packages/**'
      - 'package.json'
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install dependency
        run: yarn install
      - name: lint
        run: yarn lint
      - name: test
        run: yarn test
        env:
          CI: true
